// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSystem.Data;

#nullable disable

namespace SchoolSystem.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSystem.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AttendanceId");

                    b.ToTable("Attendances", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attendance_PersonType", "[PersonType] IN ('Student','Teacher','Employee')");

                            t.HasCheckConstraint("CK_Attendance_Status", "[AttendanceStatus] IN ('Present','Absent','Late','Excused')");
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)");

                    b.HasKey("CityId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityCode = "SA-RYD",
                            CityName = "Riyadh",
                            CountryCode = "SAU"
                        },
                        new
                        {
                            CityId = 2,
                            CityCode = "SA-JED",
                            CityName = "Jeddah",
                            CountryCode = "SAU"
                        },
                        new
                        {
                            CityId = 3,
                            CityCode = "AE-AUH",
                            CityName = "Abu Dhabi",
                            CountryCode = "ARE"
                        },
                        new
                        {
                            CityId = 4,
                            CityCode = "AE-DXB",
                            CityName = "Dubai",
                            CountryCode = "ARE"
                        },
                        new
                        {
                            CityId = 5,
                            CityCode = "OM-MSC",
                            CityName = "Muscat",
                            CountryCode = "OMN"
                        },
                        new
                        {
                            CityId = 6,
                            CityCode = "QA-DOH",
                            CityName = "Doha",
                            CountryCode = "QAT"
                        },
                        new
                        {
                            CityId = 7,
                            CityCode = "BH-MNL",
                            CityName = "Manama",
                            CountryCode = "BHR"
                        },
                        new
                        {
                            CityId = 8,
                            CityCode = "KW-KWI",
                            CityName = "Kuwait City",
                            CountryCode = "KWT"
                        },
                        new
                        {
                            CityId = 9,
                            CityCode = "YE-SAN",
                            CityName = "Sana'a",
                            CountryCode = "YEM"
                        },
                        new
                        {
                            CityId = 10,
                            CityCode = "YE-ADN",
                            CityName = "Aden",
                            CountryCode = "YEM"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryCode = "SAU",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryCode = "ARE",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryCode = "OMN",
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryCode = "QAT",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryCode = "BHR",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryCode = "KWT",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryCode = "YEM",
                            CountryName = "Yemen"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("StudentLevelLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("StudentLevelLevelId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Dates", "[StartDate] <= [EndDate] OR [StartDate] IS NULL OR [EndDate] IS NULL");
                        });

                    b.HasData(
                        new
                        {
                            CourseId = 1000,
                            CurriculumId = 101,
                            Description = "Arabic for Grade 1",
                            Name = "Arabic - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8194),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1001,
                            CurriculumId = 101,
                            Description = "Mathematics for Grade 1",
                            Name = "Mathematics - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8216),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1002,
                            CurriculumId = 101,
                            Description = "Science for Grade 1",
                            Name = "Science - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8222),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1003,
                            CurriculumId = 101,
                            Description = "English for Grade 1",
                            Name = "English - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8228),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1004,
                            CurriculumId = 101,
                            Description = "Islamic for Grade 1",
                            Name = "Islamic - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8233),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1005,
                            CurriculumId = 101,
                            Description = "Social Studies for Grade 1",
                            Name = "Social Studies - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8241),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1006,
                            CurriculumId = 101,
                            Description = "Computer for Grade 1",
                            Name = "Computer - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8247),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1007,
                            CurriculumId = 101,
                            Description = "Physical Education for Grade 1",
                            Name = "Physical Education - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8253),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1008,
                            CurriculumId = 101,
                            Description = "Art for Grade 1",
                            Name = "Art - Grade 1",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8259),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1009,
                            CurriculumId = 102,
                            Description = "Arabic for Grade 2",
                            Name = "Arabic - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8267),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1010,
                            CurriculumId = 102,
                            Description = "Mathematics for Grade 2",
                            Name = "Mathematics - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8274),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1011,
                            CurriculumId = 102,
                            Description = "Science for Grade 2",
                            Name = "Science - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8280),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1012,
                            CurriculumId = 102,
                            Description = "English for Grade 2",
                            Name = "English - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8286),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1013,
                            CurriculumId = 102,
                            Description = "Islamic for Grade 2",
                            Name = "Islamic - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8293),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1014,
                            CurriculumId = 102,
                            Description = "Social Studies for Grade 2",
                            Name = "Social Studies - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8303),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1015,
                            CurriculumId = 102,
                            Description = "Computer for Grade 2",
                            Name = "Computer - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8310),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1016,
                            CurriculumId = 102,
                            Description = "Physical Education for Grade 2",
                            Name = "Physical Education - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8316),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1017,
                            CurriculumId = 102,
                            Description = "Art for Grade 2",
                            Name = "Art - Grade 2",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8324),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1018,
                            CurriculumId = 103,
                            Description = "Arabic for Grade 3",
                            Name = "Arabic - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8330),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1019,
                            CurriculumId = 103,
                            Description = "Mathematics for Grade 3",
                            Name = "Mathematics - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8335),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1020,
                            CurriculumId = 103,
                            Description = "Science for Grade 3",
                            Name = "Science - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8341),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1021,
                            CurriculumId = 103,
                            Description = "English for Grade 3",
                            Name = "English - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8347),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1022,
                            CurriculumId = 103,
                            Description = "Islamic for Grade 3",
                            Name = "Islamic - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8353),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1023,
                            CurriculumId = 103,
                            Description = "Social Studies for Grade 3",
                            Name = "Social Studies - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8359),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1024,
                            CurriculumId = 103,
                            Description = "Computer for Grade 3",
                            Name = "Computer - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8365),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1025,
                            CurriculumId = 103,
                            Description = "Physical Education for Grade 3",
                            Name = "Physical Education - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8370),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1026,
                            CurriculumId = 103,
                            Description = "Art for Grade 3",
                            Name = "Art - Grade 3",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8377),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1027,
                            CurriculumId = 104,
                            Description = "Arabic for Grade 4",
                            Name = "Arabic - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8383),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1028,
                            CurriculumId = 104,
                            Description = "Mathematics for Grade 4",
                            Name = "Mathematics - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8389),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1029,
                            CurriculumId = 104,
                            Description = "Science for Grade 4",
                            Name = "Science - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8394),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1030,
                            CurriculumId = 104,
                            Description = "English for Grade 4",
                            Name = "English - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8400),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1031,
                            CurriculumId = 104,
                            Description = "Islamic for Grade 4",
                            Name = "Islamic - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8405),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1032,
                            CurriculumId = 104,
                            Description = "Social Studies for Grade 4",
                            Name = "Social Studies - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8412),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1033,
                            CurriculumId = 104,
                            Description = "Computer for Grade 4",
                            Name = "Computer - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8419),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1034,
                            CurriculumId = 104,
                            Description = "Physical Education for Grade 4",
                            Name = "Physical Education - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8424),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1035,
                            CurriculumId = 104,
                            Description = "Art for Grade 4",
                            Name = "Art - Grade 4",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8430),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1036,
                            CurriculumId = 105,
                            Description = "Arabic for Grade 5",
                            Name = "Arabic - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8435),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1037,
                            CurriculumId = 105,
                            Description = "Mathematics for Grade 5",
                            Name = "Mathematics - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8441),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1038,
                            CurriculumId = 105,
                            Description = "Science for Grade 5",
                            Name = "Science - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8455),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1039,
                            CurriculumId = 105,
                            Description = "English for Grade 5",
                            Name = "English - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8461),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1040,
                            CurriculumId = 105,
                            Description = "Islamic for Grade 5",
                            Name = "Islamic - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8466),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1041,
                            CurriculumId = 105,
                            Description = "Social Studies for Grade 5",
                            Name = "Social Studies - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8472),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1042,
                            CurriculumId = 105,
                            Description = "Computer for Grade 5",
                            Name = "Computer - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8478),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1043,
                            CurriculumId = 105,
                            Description = "Physical Education for Grade 5",
                            Name = "Physical Education - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8485),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1044,
                            CurriculumId = 105,
                            Description = "Art for Grade 5",
                            Name = "Art - Grade 5",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8491),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1045,
                            CurriculumId = 106,
                            Description = "Arabic for Grade 6",
                            Name = "Arabic - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8496),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1046,
                            CurriculumId = 106,
                            Description = "Mathematics for Grade 6",
                            Name = "Mathematics - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8502),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1047,
                            CurriculumId = 106,
                            Description = "Science for Grade 6",
                            Name = "Science - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8507),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1048,
                            CurriculumId = 106,
                            Description = "English for Grade 6",
                            Name = "English - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8513),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1049,
                            CurriculumId = 106,
                            Description = "Islamic for Grade 6",
                            Name = "Islamic - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8518),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1050,
                            CurriculumId = 106,
                            Description = "Social Studies for Grade 6",
                            Name = "Social Studies - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8524),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1051,
                            CurriculumId = 106,
                            Description = "Computer for Grade 6",
                            Name = "Computer - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8530),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1052,
                            CurriculumId = 106,
                            Description = "Physical Education for Grade 6",
                            Name = "Physical Education - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8535),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1053,
                            CurriculumId = 106,
                            Description = "Art for Grade 6",
                            Name = "Art - Grade 6",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8541),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1054,
                            CurriculumId = 107,
                            Description = "Arabic for Grade 7",
                            Name = "Arabic - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8546),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1055,
                            CurriculumId = 107,
                            Description = "Mathematics for Grade 7",
                            Name = "Mathematics - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8552),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1056,
                            CurriculumId = 107,
                            Description = "Science for Grade 7",
                            Name = "Science - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8557),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1057,
                            CurriculumId = 107,
                            Description = "English for Grade 7",
                            Name = "English - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8563),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1058,
                            CurriculumId = 107,
                            Description = "Islamic for Grade 7",
                            Name = "Islamic - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8568),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1059,
                            CurriculumId = 107,
                            Description = "Social Studies for Grade 7",
                            Name = "Social Studies - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8573),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1060,
                            CurriculumId = 107,
                            Description = "Computer for Grade 7",
                            Name = "Computer - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8579),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1061,
                            CurriculumId = 107,
                            Description = "Physical Education for Grade 7",
                            Name = "Physical Education - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8584),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1062,
                            CurriculumId = 107,
                            Description = "Art for Grade 7",
                            Name = "Art - Grade 7",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8590),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1063,
                            CurriculumId = 108,
                            Description = "Arabic for Grade 8",
                            Name = "Arabic - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8595),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1064,
                            CurriculumId = 108,
                            Description = "Mathematics for Grade 8",
                            Name = "Mathematics - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8601),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1065,
                            CurriculumId = 108,
                            Description = "Science for Grade 8",
                            Name = "Science - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8617),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1066,
                            CurriculumId = 108,
                            Description = "English for Grade 8",
                            Name = "English - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8623),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1067,
                            CurriculumId = 108,
                            Description = "Islamic for Grade 8",
                            Name = "Islamic - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8629),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1068,
                            CurriculumId = 108,
                            Description = "Social Studies for Grade 8",
                            Name = "Social Studies - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8634),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1069,
                            CurriculumId = 108,
                            Description = "Computer for Grade 8",
                            Name = "Computer - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8640),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1070,
                            CurriculumId = 108,
                            Description = "Physical Education for Grade 8",
                            Name = "Physical Education - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8645),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1071,
                            CurriculumId = 108,
                            Description = "Art for Grade 8",
                            Name = "Art - Grade 8",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8650),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1072,
                            CurriculumId = 109,
                            Description = "Arabic for Grade 9",
                            Name = "Arabic - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8656),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1073,
                            CurriculumId = 109,
                            Description = "Mathematics for Grade 9",
                            Name = "Mathematics - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8662),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1074,
                            CurriculumId = 109,
                            Description = "Science for Grade 9",
                            Name = "Science - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8667),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1075,
                            CurriculumId = 109,
                            Description = "English for Grade 9",
                            Name = "English - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8672),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1076,
                            CurriculumId = 109,
                            Description = "Islamic for Grade 9",
                            Name = "Islamic - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8678),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1077,
                            CurriculumId = 109,
                            Description = "Social Studies for Grade 9",
                            Name = "Social Studies - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8684),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1078,
                            CurriculumId = 109,
                            Description = "Computer for Grade 9",
                            Name = "Computer - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8690),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1079,
                            CurriculumId = 109,
                            Description = "Physical Education for Grade 9",
                            Name = "Physical Education - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8697),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1080,
                            CurriculumId = 109,
                            Description = "Art for Grade 9",
                            Name = "Art - Grade 9",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8703),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1081,
                            CurriculumId = 110,
                            Description = "Arabic for Grade 10",
                            Name = "Arabic - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8708),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1082,
                            CurriculumId = 110,
                            Description = "Mathematics for Grade 10",
                            Name = "Mathematics - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8714),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1083,
                            CurriculumId = 110,
                            Description = "Science for Grade 10",
                            Name = "Science - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8719),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1084,
                            CurriculumId = 110,
                            Description = "English for Grade 10",
                            Name = "English - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8725),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1085,
                            CurriculumId = 110,
                            Description = "Islamic for Grade 10",
                            Name = "Islamic - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8730),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1086,
                            CurriculumId = 110,
                            Description = "Social Studies for Grade 10",
                            Name = "Social Studies - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8736),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1087,
                            CurriculumId = 110,
                            Description = "Computer for Grade 10",
                            Name = "Computer - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8741),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1088,
                            CurriculumId = 110,
                            Description = "Physical Education for Grade 10",
                            Name = "Physical Education - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8752),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1089,
                            CurriculumId = 110,
                            Description = "Art for Grade 10",
                            Name = "Art - Grade 10",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8757),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1090,
                            CurriculumId = 111,
                            Description = "Arabic for Grade 11",
                            Name = "Arabic - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8763),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1091,
                            CurriculumId = 111,
                            Description = "Mathematics for Grade 11",
                            Name = "Mathematics - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8770),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1092,
                            CurriculumId = 111,
                            Description = "Science for Grade 11",
                            Name = "Science - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8776),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1093,
                            CurriculumId = 111,
                            Description = "English for Grade 11",
                            Name = "English - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8781),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1094,
                            CurriculumId = 111,
                            Description = "Islamic for Grade 11",
                            Name = "Islamic - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8786),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1095,
                            CurriculumId = 111,
                            Description = "Social Studies for Grade 11",
                            Name = "Social Studies - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8793),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1096,
                            CurriculumId = 111,
                            Description = "Computer for Grade 11",
                            Name = "Computer - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8798),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1097,
                            CurriculumId = 111,
                            Description = "Physical Education for Grade 11",
                            Name = "Physical Education - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8804),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1098,
                            CurriculumId = 111,
                            Description = "Art for Grade 11",
                            Name = "Art - Grade 11",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8810),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1099,
                            CurriculumId = 112,
                            Description = "Arabic for Grade 12",
                            Name = "Arabic - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8816),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1100,
                            CurriculumId = 112,
                            Description = "Mathematics for Grade 12",
                            Name = "Mathematics - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8822),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1101,
                            CurriculumId = 112,
                            Description = "Science for Grade 12",
                            Name = "Science - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8828),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1102,
                            CurriculumId = 112,
                            Description = "English for Grade 12",
                            Name = "English - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8834),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1103,
                            CurriculumId = 112,
                            Description = "Islamic for Grade 12",
                            Name = "Islamic - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8840),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1104,
                            CurriculumId = 112,
                            Description = "Social Studies for Grade 12",
                            Name = "Social Studies - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8845),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1105,
                            CurriculumId = 112,
                            Description = "Computer for Grade 12",
                            Name = "Computer - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8851),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1106,
                            CurriculumId = 112,
                            Description = "Physical Education for Grade 12",
                            Name = "Physical Education - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8858),
                            TeacherId = 1
                        },
                        new
                        {
                            CourseId = 1107,
                            CurriculumId = 112,
                            Description = "Art for Grade 12",
                            Name = "Art - Grade 12",
                            StartDate = new DateTime(2025, 12, 8, 0, 43, 1, 155, DateTimeKind.Local).AddTicks(8863),
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CurriculumId");

                    b.HasIndex("LevelId");

                    b.ToTable("Curriculums", (string)null);

                    b.HasData(
                        new
                        {
                            CurriculumId = 101,
                            Description = "Basic Yemeni curriculum for Grade 1",
                            LevelId = 1,
                            Name = "Yemeni Curriculum Grade 1",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 102,
                            Description = "Basic Yemeni curriculum for Grade 2",
                            LevelId = 2,
                            Name = "Yemeni Curriculum Grade 2",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 103,
                            Description = "Basic Yemeni curriculum for Grade 3",
                            LevelId = 3,
                            Name = "Yemeni Curriculum Grade 3",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 104,
                            Description = "Basic Yemeni curriculum for Grade 4",
                            LevelId = 4,
                            Name = "Yemeni Curriculum Grade 4",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 105,
                            Description = "Basic Yemeni curriculum for Grade 5",
                            LevelId = 5,
                            Name = "Yemeni Curriculum Grade 5",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 106,
                            Description = "Basic Yemeni curriculum for Grade 6",
                            LevelId = 6,
                            Name = "Yemeni Curriculum Grade 6",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 107,
                            Description = "Basic Yemeni curriculum for Grade 7",
                            LevelId = 7,
                            Name = "Yemeni Curriculum Grade 7",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 108,
                            Description = "Basic Yemeni curriculum for Grade 8",
                            LevelId = 8,
                            Name = "Yemeni Curriculum Grade 8",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 109,
                            Description = "Basic Yemeni curriculum for Grade 9",
                            LevelId = 9,
                            Name = "Yemeni Curriculum Grade 9",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 110,
                            Description = "Basic Yemeni curriculum for Grade 10",
                            LevelId = 10,
                            Name = "Yemeni Curriculum Grade 10",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 111,
                            Description = "Basic Yemeni curriculum for Grade 11",
                            LevelId = 11,
                            Name = "Yemeni Curriculum Grade 11",
                            Semester = "First"
                        },
                        new
                        {
                            CurriculumId = 112,
                            Description = "Basic Yemeni curriculum for Grade 12",
                            LevelId = 12,
                            Name = "Yemeni Curriculum Grade 12",
                            Semester = "First"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SocialStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("BuildingNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LocationId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            BuildingNo = "1",
                            CityId = 1,
                            CountryId = 1,
                            Street = "Default St"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentId"));

                    b.Property<int?>("ChildrenInSchool")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ParentId");

                    b.HasIndex("LocationId");

                    b.ToTable("Parents", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentCourseEnrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Attendance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FinalGrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourseEnrollments", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentGrade", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("ExamType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("StudentId", "CourseId", "ExamType");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentGrades", (string)null);
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LevelId");

                    b.ToTable("StudentLevels", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudentLevel_Stage", "[Stage] IN (N'ابتدائي', N'أساسي', N'ثانوي')");
                        });

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            LevelName = "Grade 1",
                            LevelNumber = 1,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 2,
                            LevelName = "Grade 2",
                            LevelNumber = 2,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 3,
                            LevelName = "Grade 3",
                            LevelNumber = 3,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 4,
                            LevelName = "Grade 4",
                            LevelNumber = 4,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 5,
                            LevelName = "Grade 5",
                            LevelNumber = 5,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 6,
                            LevelName = "Grade 6",
                            LevelNumber = 6,
                            Stage = "ابتدائي"
                        },
                        new
                        {
                            LevelId = 7,
                            LevelName = "Grade 7",
                            LevelNumber = 7,
                            Stage = "أساسي"
                        },
                        new
                        {
                            LevelId = 8,
                            LevelName = "Grade 8",
                            LevelNumber = 8,
                            Stage = "أساسي"
                        },
                        new
                        {
                            LevelId = 9,
                            LevelName = "Grade 9",
                            LevelNumber = 9,
                            Stage = "أساسي"
                        },
                        new
                        {
                            LevelId = 10,
                            LevelName = "Grade 10",
                            LevelNumber = 10,
                            Stage = "ثانوي"
                        },
                        new
                        {
                            LevelId = 11,
                            LevelName = "Grade 11",
                            LevelNumber = 11,
                            Stage = "ثانوي"
                        },
                        new
                        {
                            LevelId = 12,
                            LevelName = "Grade 12",
                            LevelNumber = 12,
                            Stage = "ثانوي"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationDegree")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfVacations")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("SocialStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartWorkingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeachingSubject")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.HasIndex("LocationId");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            DateOfBirth = new DateTime(1985, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.ahmed@school.com",
                            FirstName = "Ali",
                            LastName = "Ahmed",
                            LocationId = 1,
                            PhoneNumber = "555123456",
                            Salary = 4000.00m,
                            StartWorkingDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Activity", b =>
                {
                    b.HasOne("SchoolSystem.Models.Employee", "Supervisor")
                        .WithMany("ActivitiesSupervised")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SchoolSystem.Models.Course", b =>
                {
                    b.HasOne("SchoolSystem.Models.Curriculum", "Curriculum")
                        .WithMany("Courses")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.StudentLevel", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentLevelLevelId");

                    b.HasOne("SchoolSystem.Models.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Curriculum");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolSystem.Models.Curriculum", b =>
                {
                    b.HasOne("SchoolSystem.Models.StudentLevel", "StudentLevel")
                        .WithMany("Curriculums")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentLevel");
                });

            modelBuilder.Entity("SchoolSystem.Models.Employee", b =>
                {
                    b.HasOne("SchoolSystem.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SchoolSystem.Models.Location", b =>
                {
                    b.HasOne("SchoolSystem.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SchoolSystem.Models.Parent", b =>
                {
                    b.HasOne("SchoolSystem.Models.Location", "Location")
                        .WithMany("Parents")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SchoolSystem.Models.Student", b =>
                {
                    b.HasOne("SchoolSystem.Models.StudentLevel", "StudentLevel")
                        .WithMany("Students")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Location", "Location")
                        .WithMany("Students")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Parent");

                    b.Navigation("StudentLevel");
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentCourseEnrollment", b =>
                {
                    b.HasOne("SchoolSystem.Models.Course", "Course")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Student", "Student")
                        .WithMany("StudentEnrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentGrade", b =>
                {
                    b.HasOne("SchoolSystem.Models.Course", "Course")
                        .WithMany("Grades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolSystem.Models.Teacher", b =>
                {
                    b.HasOne("SchoolSystem.Models.Location", "Location")
                        .WithMany("Teachers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SchoolSystem.Models.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("SchoolSystem.Models.Course", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("SchoolSystem.Models.Curriculum", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SchoolSystem.Models.Employee", b =>
                {
                    b.Navigation("ActivitiesSupervised");
                });

            modelBuilder.Entity("SchoolSystem.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Parents");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("SchoolSystem.Models.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SchoolSystem.Models.Student", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("StudentEnrollments");
                });

            modelBuilder.Entity("SchoolSystem.Models.StudentLevel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Curriculums");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolSystem.Models.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
