CREATE DATABASE SCHOOLMANAGEMENTDB;

GO
USE SCHOOLMANAGEMENTDB;

GO

CREATE TABLE PARENTS(
  PARENTSID INT PRIMARY KEY IDENTITY(1, 1),
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  DATEOFBIRTH DATE,
  LOCATIONID INT NOT NULL,
  PHONENUMBER NVARCHAR(15),
  EMAIL NVARCHAR(100),
  CHILDRENINSCHOOL INT
);

GO

CREATE TABLE COUNTRIES(
  COUNTRYID INT PRIMARY KEY IDENTITY(1, 1),
  COUNTRYCODE NCHAR(20) NOT NULL UNIQUE,
  COUNTRYNAME NVARCHAR(50) NOT NULL,
);

GO

CREATE TABLE CITIES(
  CITYID INT PRIMARY KEY IDENTITY(1, 1),
  CITYCODE NCHAR(20) NOT NULL UNIQUE,
  CITYNAME NVARCHAR(50) NOT NULL,
);

GO

CREATE TABLE LOCATIONS(
  LOCATIONID INT PRIMARY KEY IDENTITY(9, 4),
  COUNTRYID INT NOT NULL,
  CITYID INT NOT NULL,
  STREET VARCHAR(50) NOT NULL,
  BUILDINGNO VARCHAR(30) NOT NULL,
  CONSTRAINT FK_LOCATION_COUNTRY FOREIGN KEY (COUNTRYID) REFERENCES COUNTRIES(COUNTRYID),
  CONSTRAINT FK_LOCATION_CITY FOREIGN KEY (CITYID) REFERENCES CITIES(CITYID)
);

GO

CREATE TABLE STUDENTS(
  STUDENTSID INT PRIMARY KEY IDENTITY(1, 1),
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  DATEOFBIRTH DATE,
  LOCATIONID INT NOT NULL,
  PARENTID INT NOT NULL,
  CONSTRAINT FK_STUDENT_PARENT FOREIGN KEY (PARENTID) REFERENCES PARENTS(PARENTSID)
);

GO

ALTER TABLE PARENTS
  ADD CONSTRAINT FK_PARENTS_LOCATION FOREIGN KEY (
    LOCATIONID
  )
    REFERENCES LOCATIONS(
      LOCATIONID
    );

GO

ALTER TABLE STUDENTS
  ADD CONSTRAINT FK_STUDENTS_LOCATION FOREIGN KEY (
    LOCATIONID
  )
    REFERENCES LOCATIONS(
      LOCATIONID
    );

CREATE TABLE COURSES (
  COURSEID INT PRIMARY KEY IDENTITY(1, 1),
  NAME NVARCHAR(100) NOT NULL,
  DESCRIPTION NVARCHAR(255),
  STARTDATE DATE,
  ENDDATE DATE,
  TEACHERID INT NULL
);

CREATE TABLE TEACHERS (
  TEACHERID INT PRIMARY KEY IDENTITY(1, 1),
  FIRSTNAME NVARCHAR(50) NOT NULL,
  LASTNAME NVARCHAR(50) NOT NULL,
  DATEOFBIRTH DATE,
  LOCATIONID INT NOT NULL,
  SALARY DECIMAL(10, 2),
  EDUCATIONDEGREE NVARCHAR(100) CHECK (EDUCATIONDEGREE IN('Bachelor degree', 'Master Degree')),
  TEACHINGSUBJECT NVARCHAR(100),
  STARTWORKINGDATE DATE,
  NUMBEROFVACATIONS INT,
  PHONENUMBER NVARCHAR(15),
  EMAIL NVARCHAR(100) UNIQUE,
  SOCIALSTATUS NVARCHAR(50) CHECK (SOCIALSTATUS IN ('Single', 'Married')),
);

ALTER TABLE TEACHERS
  ADD CONSTRAINT FK_TEACHERS_LOCATION FOREIGN KEY (
    LOCATIONID
  )
    REFERENCES LOCATIONS(
      LOCATIONID
    );

ALTER TABLE COURSES
  ADD CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY(
    TEACHERID
  )
    REFERENCES TEACHERS(
      TEACHERID
    );

CREATE TABLE STUDENTGRADES(
  STUDENTID INT NOT NULL,
  COURSEID INT NOT NULL,
  EXAMTYPE NVARCHAR(50) NOT NULL,
  MARK DECIMAL(5, 2) CHECK (MARK >=0 AND MARK <= 100),
 
  -- composite primary key
  PRIMARY KEY (STUDENTID, COURSEID, EXAMTYPE),
  CONSTRAINT FK_GRADE_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTSID),
  CONSTRAINT FK_GRADE_COURSE FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);

GO

CREATE TABLE ATTENDANCE (
  ATTENDANCEID INT PRIMARY KEY IDENTITY(1, 1),
  PERSONID INT NOT NULL,
  PERSONTYPE NVARCHAR(20) NOT NULL CHECK (PERSONTYPE IN ('Student', 'Teacher', 'Emp')),
  ATTENDANCEDATE DATE NOT NULL,
  ATTENDANCESTATUS NVARCHAR(20) NOT NULL CHECK (ATTENDANCESTATUS IN ('Present', 'Absent', 'Late', 'Excused')),
  UNIQUE (PERSONID, PERSONTYPE, ATTENDANCEDATE)
);

GO

CREATE TABLE EMPLOYEES (
  EMPLOYEEID INT PRIMARY KEY IDENTITY(1, 1),
  FIRSTNAME NVARCHAR(50) NOT NULL,
  LASTNAME NVARCHAR(50) NOT NULL,
  DATEOFBIRTH DATE,
  LOCATIONID INT NOT NULL,
  PHONENUMBER NVARCHAR(15),
  EMAIL NVARCHAR(100) UNIQUE,
  JOPTITLE NVARCHAR(50),
  DEPARTMENT NVARCHAR(50),
  HIREDATE DATE,
  SALARY DECIMAL(10, 2),
  SOCIALSTATUS NVARCHAR(50) CHECK (SOCIALSTATUS IN ('Single', 'Married'))
);

ALTER TABLE EMPLOYEES
  ADD CONSTRAINT FK_EMPLOYEES_LOCATION FOREIGN KEY (
    LOCATIONID
  )
    REFERENCES LOCATIONS(
      LOCATIONID
    );

-- ########################################################################################
CREATE TABLE ACTIVITIES(
  ACTIVITYID INT PRIMARY KEY IDENTITY(1, 1),
  ACTIVITYNAME NVARCHAR(10),
  DESCRIPTION NVARCHAR(100),
  SCHEDULE NVARCHAR(100),
  LOCATION NVARCHAR(100)
);

CREATE TABLE CURRICULUM(
  ID INT PRIMARY KEY IDENTITY(1, 1),
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION NVARCHAR(100)
);

CREATE TABLE STUDENTCOUSEENROLLMENT(
  STUDENTID INT NOT NULL,
  COURSEID INT NOT NULL,
  ENROLLMENTDATE DATE,
  ATTENDANCE NVARCHAR(20),
  FINALGRADE VARCHAR(50),
  PRIMARY KEY (STUDENTID, COURSEID),
  CONSTRAINT FK_STUDENTCOURSEENROLLMENT_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTSID),
  CONSTRAINT FK_STUDENTCOURSEENROLLMENT_COURSE FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);

ALTER TABLE COURSES
  ADD CURRICULUMID INT NULL;

ALTER TABLE COURSES
  ADD CONSTRAINT FK_COURSES_CURRICULUM FOREIGN KEY (
    CURRICULUMID
  )
    REFERENCES CURRICULUM(
      ID
    );

ALTER TABLE ACTIVITIES
  ADD SUPERVISORID INT NULL;

ALTER TABLE ACTIVITIES
  ADD CONSTRAINT FK_ACTIVITIES_SUPERVISOR FOREIGN KEY (
    SUPERVISORID
  )
    REFERENCES EMPLOYEES(
      EMPLOYEEID
    );